name: pipeline
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.3.1
  - numpy=1.18.5
  - pip=20.1.1
  - python=3.8.3
  - pytorch=1.10.1
  - pip:
      - gensim==3.8.3
      - simpletransformers~=0.63.4
