name: pipeline
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.3.1
  - numpy=1.18.5
  - pip=20.1.1
  - python=3.8.3
  - pytorch=1.10.1
  - texsoup=0.3.1
  - nltk=3.4.5
  - pip:
      - gensim==3.8.3
      - simpletransformers~=0.63.4
      - bibtexparser==1.2.0
      - anytree==2.8.0
      - rank-bm25==0.2.2